---
id: training
name: Internal training

content:
  url: https://raw.githubusercontent.com/osevg/workshopper-content/master

vars:
  USER_NAME: "(email)"
  USER_PASSWORD: "(email)"
  PARKSMAP_IMAGENAME: "parksmap"
  PARKSMAP_VERSION: "1.2.0"
  PARKSMAP_PY: true
  NATIONALPARKS_VERSION: "1.2.1"
  MLBPARKS_VERSION: "1.0.0"
  DOWNLOAD_CLIENT_WINDOWS: https://github.com/openshift/origin/releases/download/v1.5.0/openshift-origin-client-tools-v1.5.0-031cbe4-windows.zip
  DOWNLOAD_CLIENT_MAC: https://github.com/openshift/origin/releases/download/v1.5.0/openshift-origin-client-tools-v1.5.0-031cbe4-mac.zip
  DOWNLOAD_CLIENT_LIN64: https://github.com/openshift/origin/releases/download/v1.5.0/openshift-origin-client-tools-v1.5.0-031cbe4-linux-64bit.tar.gz
  OC_VERSION: "oc v1.5.0+031cbe4\nkubernetes v1.5.2+43a9be4"
  CONSOLE_ADDRESS: console.westford.pixy.io:8443
  ROUTER_ADDRESS: apps.westford.pixy.io
  GIT_HOST: github
  NO_USER_PROJECT: true

modules:
  activate:
  - install
  - explore
  - parksmap-architecture
  - docker
  - scaling
  - routes
  - permissions
  - python
  - databases-py
  - application-health
  - codechanges
  - templates
